### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by Coimbra1984** [authpass/biometric_storage#14]
Hi,

my build for android fails, I get the following output, do you have any ideas?

D:\work\flutter_leakagePro\android>gradlew clean build

Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :app:processDebugMainManifest
[androidx.test.espresso:espresso-core:3.2.0] C:\Users\marku\.gradle\caches\transforms-2\files-2.1\b57e330d5fcdd60ce3b36badc90dc06f\espresso-core-3.2.0\AndroidManifest.xml Warning:
        Package name 'androidx.test.espresso' used in: androidx.test.espresso:espresso-core:3.2.0, androidx.test.espresso:espresso-idling-resource:3.2.0.

> Task :biometric_storage:kaptGenerateStubsDebugKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/d22d204f3e998a9e7c9d88e394ac0ba5/jetified-kotlin-stdlib-jdk7-1.3.72.jar (version 1.3)
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/65c169ff90c96e3f402cb10ee8492979/jetified-kotlin-reflect-1.4.10.jar (version 1.4)
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/36887588733dfdc92602d11f3e7f2d2b/jetified-kotlin-stdlib-1.4.10.jar (version 1.4)
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/4abdcab0f6108d9fa2aabea9c8a14bec/jetified-kotlin-stdlib-common-1.4.10.jar (version 1.4)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

> Task :biometric_storage:kaptDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/d22d204f3e998a9e7c9d88e394ac0ba5/jetified-kotlin-stdlib-jdk7-1.3.72.jar (version 1.3)
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/65c169ff90c96e3f402cb10ee8492979/jetified-kotlin-reflect-1.4.10.jar (version 1.4)
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/36887588733dfdc92602d11f3e7f2d2b/jetified-kotlin-stdlib-1.4.10.jar (version 1.4)
    C:/Users/marku/.gradle/caches/transforms-2/files-2.1/4abdcab0f6108d9fa2aabea9c8a14bec/jetified-kotlin-stdlib-common-1.4.10.jar (version 1.4)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: [kapt] An exception occurred: java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at com.squareup.moshi.kotlin.codegen.api.ProguardConfig$writeTo$2$2.<init>(ProguardRules.kt)
        at com.squareup.moshi.kotlin.codegen.api.ProguardConfig$writeTo$2$2.<clinit>(ProguardRules.kt)
        at com.squareup.moshi.kotlin.codegen.api.ProguardConfig.writeTo(ProguardRules.kt:83)
        at com.squareup.moshi.kotlin.codegen.api.ProguardConfig.writeTo(ProguardRules.kt:51)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:137)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:230)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:188)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:81)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:555)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:546)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':biometric_storage:kaptDebugKotlin'.
> Compilation error. See log for more details

**Comment by Coimbra1984** [comment]
Okay, I fixed it.
I had to change the kotlin version to
ext.kotlin_version = '1.4.10'
in build.gradle

**Comment by syky27** [comment]
@Coimbra1984 thanks or sharing!

**Comment by arjuntare** [comment]
> Okay, I fixed it.
> I had to change the kotlin version to
> ext.kotlin_version = '1.4.10'
> in build.gradle

This worked!
